const usersConstants = {
	GET_ALL_SUCCESS: 		'GET_ALL_SUCCESS',
	GET_ALL_FAILURE: 		'GET_ALL_FAILURE',
	REGISTER_SUCCESS: 		'REGISTER_SUCCESS',
	REGISTER_FAILURE: 		'REGISTER_FAILURE',
	GET_USER_SUCCESS: 		'GET_USER_SUCCESS',
	GET_USER_FAILURE: 		'GET_USER_FAILURE',
	UPDATE_USER_SUCCESS: 	'UPDATE_USER_SUCCESS',
	UPDATE_USER_FAILURE: 	'UPDATE_USER_FAILURE'
}

export default usersConstants